repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=100"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.7", "types-requests", "types-setuptools"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [
          "-r", ".",
          "-s", "B101",
          "-x", "tests,discovery-engine-2cat,proofengine,examples,fixtures,out,dist,demo,demo_repo,out_lab",
          "-lll",
          "-iii",
          "--exit-zero"
        ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: conflict-marker-check
        name: Detect merge conflict markers
        entry: python scripts/check_conflict_markers.py
        language: system
        pass_filenames: false
      - id: validate-schemas
        name: Validate JSON Schemas and Examples
        entry: python scripts/test_roundtrip.py
        language: system
        files: ^(specs/v0.1/.*\.json|examples/v0.1/.*\.json)$
        pass_filenames: false
      - id: lock-present
        name: Ensure requirements.lock present
        entry: bash -lc 'test -s requirements.lock'
        language: system
        pass_filenames: false
