name: "Bench Pack"
description: "Build benchmark pack with metrics and documentation"

steps:
  - type: "CollectSeeds"
    name: "CollectSeeds"
    description: "Collect benchmark seeds and metrics"
    params:
      sources: ["bench/metrics/**/*.json"]
      output_dir: "out/bench"

  - type: "ComputeMerkle"
    name: "ComputeMerkle"
    description: "Compute Merkle root for integrity"
    params:
      chunk_size: 65536

  - type: "RenderDocs"
    name: "OnePager"
    description: "Generate one-pager documentation"
    params:
      template_path: null
      output_file: "ONEPAGER.md"

  - type: "PackZip"
    name: "Zip"
    description: "Create ZIP archive"
    params:
      include_manifest: true
      include_merkle: true
      zip_name: "{pack_name}-{version}.zip"

  - type: "SignArtifact"
    name: "Sign"
    description: "Sign the pack (optional in CI)"
    params:
      enabled: false  # Disabled for CI smoke test
      provider: "cosign"
      required: false
