pack:
  version: "v0.2.0"
  pack_name: "public-bench"
  out_dir: "dist"
  zip_name: "{pack_name}-{version}.zip"
  include_manifest: true
  include_merkle: true

logging:
  level: "INFO"
  json_mode: false
  gha_annotations: true

metrics:
  sources: ["bench/metrics/**/*.json"]
  include_aggregates: false
  weight_key: "n_items"
  dedup: "first"
  backend: "auto"
  reduce_policy: "intersect"
  bounded_metrics: ["coverage_gain", "novelty_avg"]
  schema_path: "schema/summary.schema.json"

merkle:
  chunk_size: 65536

sign:
  enabled: false
  provider: "cosign"
  key_ref: null
  required: false

docs:
  onepager:
    template_path: null
    output_file: "ONEPAGER.md"

sbom:
  path: null

capabilities:
  allowlist: []
  denylist: []
  registry:
    - id: "hs-tree"
      module: "pefc.capabilities.handlers.hstree:HSTreeHandler"
      enabled: true
      params: {}
    - id: "opa-rego"
      module: "pefc.capabilities.handlers.opa:OPAHandler"
      enabled: true
      params:
        policy_dir: "policies"
        query: "data.pefc.allow"
    - id: "ids-synth"
      module: "pefc.capabilities.handlers.ids:IDSHandler"
      enabled: true
      params:
        n_seeds: 24

pipelines:
  default: "bench_pack"
  defs:
    bench_pack:
      name: "Bench Pack"
      steps:
        - type: "collect"
          name: "CollectSeeds"
          params: {}
        - type: "compute_merkle"
          name: "ComputeMerkle"
        - type: "render_docs"
          name: "OnePager"
        - type: "pack_zip"
          name: "Zip"
        - type: "sign"
          name: "Sign"
        - type: "capability"
          name: "RunProofs"
          params:
            capabilities: ["hs-tree"]

profiles:
  dev:
    logging:
      level: "DEBUG"
      json_mode: true
    sign:
      enabled: false

  hardening:
    logging:
      level: "INFO"
      json_mode: true
    sign:
      enabled: true
      required: true
      key_ref: "${COSIGN_KEY_REF:-k8s://cosign/pubbench}"

  partner:
    metrics:
      sources: ["partner/metrics/**/*.json"]
    capabilities:
      allowlist: ["hs-tree", "ids-synth"]
      denylist: ["opa-rego"]
