"""
Event bus and structured telemetry for PEFC.
Provides EventBus, sinks, and event types for structured telemetry.
"""

from .event_bus import EventBus, EventBusConfig
from .sinks import (
    StdoutJSONLSink,
    FileJSONLSink,
    MemorySink,
    EventSink,
    RotatingFileSink,
)
from .types import (
    EventType,
    EventLevel,
    Event,
    OrchestratorEvent,
    AEEvent,
    CEGISEvent,
    VerifyEvent,
    BudgetEvent,
    IncidentEvent,
    PCAPEvent,
    MetricsEvent,
    create_event,
    create_orchestrator_start_event,
    create_orchestrator_end_event,
    create_ae_step_event,
    create_ae_concept_emitted_event,
    create_cegis_iter_start_event,
    create_cegis_iter_end_event,
    create_cegis_iter_refine_event,
    create_cegis_iter_converged_event,
    create_verify_attempt_event,
    create_verify_result_event,
    create_budget_overrun_event,
    create_incident_event,
    create_pcap_emitted_event,
    create_metrics_snapshot_event,
)
from .manifest import AuditManifest, MerkleTree
from .pcap import PCAPWriter, PCAPSchema, PCAPManager

__all__ = [
    "EventBus",
    "EventBusConfig",
    "StdoutJSONLSink",
    "FileJSONLSink",
    "MemorySink",
    "EventSink",
    "RotatingFileSink",
    "EventType",
    "EventLevel",
    "Event",
    "OrchestratorEvent",
    "AEEvent",
    "CEGISEvent",
    "VerifyEvent",
    "BudgetEvent",
    "IncidentEvent",
    "PCAPEvent",
    "MetricsEvent",
    "create_event",
    "create_orchestrator_start_event",
    "create_orchestrator_end_event",
    "create_ae_step_event",
    "create_ae_concept_emitted_event",
    "create_cegis_iter_start_event",
    "create_cegis_iter_end_event",
    "create_cegis_iter_refine_event",
    "create_cegis_iter_converged_event",
    "create_verify_attempt_event",
    "create_verify_result_event",
    "create_budget_overrun_event",
    "create_incident_event",
    "create_pcap_emitted_event",
    "create_metrics_snapshot_event",
    "AuditManifest",
    "MerkleTree",
    "PCAPWriter",
    "PCAPSchema",
    "PCAPManager",
]
