name: CI
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop -c pre-commit run -a
  pytest:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop -c python -m pip install -e .
      - run: nix develop -c pytest -q
  build-cli:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build .#xme && ls -l result/
  sbom:
    runs-on: ubuntu-latest
    needs: build-cli
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop -c bash -lc 'mkdir -p sbom && syft dir:. -o spdx-json > sbom/sbom.spdx.json'
      - uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom/sbom.spdx.json }
  docker-build:
    runs-on: ubuntu-latest
    needs: build-cli
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with: { context: ., push: false, tags: xme/dev:latest }
  verify-2cat:
    runs-on: ubuntu-latest
    needs: build-cli
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Verify 2cat pack (skipped by default)
        env:
          FORCE_VERIFY_2CAT: "0"
        run: nix develop -c bash -lc 'bash scripts/verify_2cat_pack.sh'
  attest:
    if: ${{ secrets.COSIGN_KEY != '' }}
    runs-on: ubuntu-latest
    needs: [docker-build, sbom]
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3
      - run: cosign version
      - run: echo "Attest placeholder - wire your registry and key"