name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Use Nix dev shell
        run: nix develop -c bash -lc "python -V && pip -V"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint (non-blocking during bootstrap)
        run: |
          ruff check . || true
          ruff format --check . || true
      - name: Type check
        run: |
          mypy pefc || true
      - name: Tests (smoke)
        run: pytest -q tests/test_smoke.py

  sbom-and-attest:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom.spdx.json
          format: spdx-json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Create provenance predicate
        run: |
          echo '{"predicateType":"https://slsa.dev/provenance/v1","buildType":"github-actions"}' > predicate.json
      - name: Attest SBOM
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign attest --predicate predicate.json --type slsaprovenance --key github://actions sbom.spdx.json || true

  verify-2cat-pack:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Verify 2cat vendor pack offline
        run: |
          python scripts/verify_2cat_pack.py --zip artifacts/spec_pack_v0.2-pre.zip --sha256 artifacts/spec_pack_v0.2-pre.sha256