name: orchestrator-e2e

on:
  push:
    branches: [ feature/events-v1 ]
  pull_request:
    branches: [ feature/events-v1 ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (locked)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.lock ]; then pip install -r requirements.lock; fi
      - name: Run lab demo
        env:
          AUDIT_DIR: _audit_ci
          SEED: 123
          TIME_BUDGET: 5
          MAX_ITERS: 2
          KPI_THRESHOLD: 0.6
        run: |
          bash scripts/demo_orchestrator.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-e2e-artifacts
          path: |
            _audit_ci/**/journal.jsonl
            _audit_ci/**/metrics.json
            _audit_ci/**/manifest.json


