name: pack-verify

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-tools
        run: python -m pip install --upgrade pip pip-tools
      - name: Enforce requirements.lock
        run: |
          test -f requirements.lock
      - name: Install locked deps
        run: |
          python -m pip install -r requirements.lock
      - name: Build deterministic pack
        env:
          TZ: UTC
          PYTHONHASHSEED: '42'
          SOURCE_DATE_EPOCH: '1700000000'
        run: |
          python -m pefc.pack.cli build --config scripts/pack_inputs.example.json --audit-dir out_ci --seed 42
      - name: Locate latest run_dir
        id: findrun
        run: |
          RUN_DIR=$(ls -td out_ci/r-* | head -n1)
          echo "run_dir=$RUN_DIR" >> $GITHUB_OUTPUT
      - name: Upload pack artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack-artifacts
          path: |
            ${{ steps.findrun.outputs.run_dir }}/manifest.json
            ${{ steps.findrun.outputs.run_dir }}/merkle.json
            ${{ steps.findrun.outputs.run_dir }}/provenance.json
            ${{ steps.findrun.outputs.run_dir }}/verdict.json
            ${{ steps.findrun.outputs.run_dir }}/logs.jsonl
            ${{ steps.findrun.outputs.run_dir }}/incidents.jsonl

  run-proofs:
    runs-on: ubuntu-latest
    needs: build-pack
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install locked deps
        run: |
          python -m pip install -r requirements.lock
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifacts
          path: dist_artifacts
      - name: Verify merkle root matches manifest
        run: |
          python - <<'PY'
import json, sys
from pathlib import Path
rd = Path('dist_artifacts')
m = json.loads((rd/'manifest.json').read_text())
merkle = json.loads((rd/'merkle.json').read_text())
assert merkle.get('root') == m.get('merkle_root'), 'Merkle root mismatch'
print('OK merkle==manifest')
PY

  merkle-verify:
    runs-on: ubuntu-latest
    needs: build-pack
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install locked deps
        run: |
          python -m pip install -r requirements.lock
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifacts
          path: dist_artifacts
      - name: Proof-check one file (if present)
        run: |
          python - <<'PY'
import json
from pathlib import Path
rd = Path('dist_artifacts')
merkle = json.loads((rd/'merkle.json').read_text())
order = merkle.get('order', [])
assert isinstance(order, list)
print('OK merkle order size', len(order))
PY

  sign-provenance:
    runs-on: ubuntu-latest
    needs: [build-pack]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install locked deps
        run: |
          python -m pip install -r requirements.lock
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifacts
          path: dist_artifacts
      - name: Mock sign provenance (dry-run)
        run: |
          python - <<'PY'
import os
from pathlib import Path
from pefc.pack.signing import sign_with_cosign
p = Path('dist_artifacts/provenance.json')
sig = sign_with_cosign(p, key_ref=None, dry_run=True)
print('SIG', sig)
PY
      - name: Upload signed provenance
        uses: actions/upload-artifact@v4
        with:
          name: signed-provenance
          path: dist_artifacts/provenance.json.sig

  drift-check:
    runs-on: ubuntu-latest
    needs: [build-pack]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install locked deps
        run: |
          python -m pip install -r requirements.lock
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifacts
          path: dist_artifacts
      - name: Drift check vs baseline
        env:
          DRIFT_ACCEPTED: ${{ secrets.DRIFT_ACCEPTED }}
        run: |
          python scripts/pack_drift_check.py --artifacts dist_artifacts --baseline baselines/pack.merkle.json






