name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Enforce requirements.lock
        run: test -f requirements.lock
      - name: Install (locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.lock
      - name: Hermetic env
        run: |
          echo "TZ=UTC" >> $GITHUB_ENV
          echo "PYTHONHASHSEED=42" >> $GITHUB_ENV
          echo "SOURCE_DATE_EPOCH=1700000000" >> $GITHUB_ENV
      - name: Build deterministic pack (no-network)
        env:
          TZ: UTC
          PYTHONHASHSEED: '42'
          SOURCE_DATE_EPOCH: '1700000000'
        run: |
          python -m pefc.pack.cli build --config scripts/pack_inputs.example.json --audit-dir out_release --seed 42 --no-network
      - name: Locate run_dir
        id: findrun
        run: |
          RUN_DIR=$(ls -td out_release/r-* | head -n1)
          echo "run_dir=$RUN_DIR" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload audit artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.findrun.outputs.run_dir }}/manifest.json
            ${{ steps.findrun.outputs.run_dir }}/merkle.json
            ${{ steps.findrun.outputs.run_dir }}/provenance.json
            ${{ steps.findrun.outputs.run_dir }}/verdict.json
            ${{ steps.findrun.outputs.run_dir }}/logs.jsonl
            ${{ steps.findrun.outputs.run_dir }}/incidents.jsonl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




